name: Deploy
on: 
    workflow_dispatch: 
        inputs: 
            environment: 
                type: environment
            Release_Version: 
                type: string
                required: true
jobs: 
    Build_images:
        environment: ${{github.event.inputs.environment}}
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: downloading release assets... 
              uses: robinraju/release-downloader@v1.9
              with: 
                repository: ${{ github.repository }}
                tag: "v${{github.event.inputs.Release_Version}}"
                fileName: "app-${{github.event.inputs.Release_Version}}.zip"
                extract: false
            - run: |
                 unzip "app-${{github.event.inputs.Release_Version}}.zip"
                 ls
                 pwd
            - name: Build & push Docker image
              uses: mr-smithers-excellent/docker-build-push@v5
              with:
                   image: pradeep0877/student-management-app
                   tags: ${{github.run_number}}
                   registry: docker.io
                   dockerfile: Dockerfile
                   username: ${{ secrets.DOCKER_USERNAME }}
                   password: ${{ secrets.DOCKER_PASSWORD }}
    Deploy_to_Cloud_Rum: 
       needs: Build_images
       environment: ${{github.event.inputs.environment}}
       runs-on: ubuntu-latest
       steps: 
          - name: Setup Cloud cli
            uses: google-github-actions/setup-gcloud@v0.2.0
            with:
             project_id: mindful-backup-412805
             service_account_key: ${{ secrets.GCP_SA_KEY }}
             export_default_credentials: true
          -  name: Deploy to Cloud Run
             id: deploy
             uses: google-github-actions/deploy-cloudrun@v0.4.0
             with:
               service: sma-app
               image: "pradeep0877/student-management-app:89"
               region: us-east1
          - name: Show Output
            run: echo ${{ steps.deploy.outputs.url }}
            
      
