name: github-actions-1
on: 
  push: 
    branches: [main]
jobs: 
   Build: 
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
         java-version: '17'
         distribution: 'temurin'
      - name: Run the Maven verify phase
        run: mvn package
      - name: publishing artifact
        uses: actions/upload-artifact@v2
        with: 
          name: student_Management_system
          path: target/*.jar
